# Generated by Django 3.0.5 on 2020-04-12 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('task_url', models.URLField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('task_source', models.CharField(blank=True, max_length=50, null=True)),
                ('task_deadline', models.DateTimeField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField()),
                ('feedback_content', models.TextField(blank=True, max_length=1000, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('sender', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdapp.Task')),
            ],
        ),
    ]
